"""Detection signals for Provenance Guard.

Signal 1 (this milestone): stylometric heuristics — a deterministic, pure-Python
structural measure. Higher score = more AI-like.

Signal 2 (LLM / Groq) is added in Milestone 4.
"""

import json
import os
import re

from dotenv import load_dotenv

load_dotenv()

# Below this word count, stylometric statistics (variance, TTR) are unstable.
MIN_WORDS_FOR_STYLOMETRY = 25

LLM_MODEL = "llama-3.3-70b-versatile"

_SENTENCE_SPLIT = re.compile(r"[.!?]+")
_WORD_RE = re.compile(r"[A-Za-z']+")
# Punctuation-mark *types* a human writer might reach for.
_PUNCT_MARKS = ".,;:!?\"'()[]{}—–-…"


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


def _mean(xs):
    return sum(xs) / len(xs) if xs else 0.0


def _std(xs):
    if len(xs) < 2:
        return 0.0
    m = _mean(xs)
    return (sum((x - m) ** 2 for x in xs) / len(xs)) ** 0.5


def stylometric_score(text):
    """Score the structural 'shape' of `text`.

    Returns a dict with the combined AI-likeness `score` in [0, 1] (higher =
    more AI-like) plus the raw sub-metrics, for the audit log and debugging.

    Each sub-metric maps monotonically to an AI-likeness contribution:
      - low sentence-length variation  -> AI-like (uniform)
      - low type-token ratio           -> AI-like (repetitive vocabulary)
      - few distinct punctuation types  -> AI-like (regular)
    """
    text = text or ""
    words = _WORD_RE.findall(text.lower())
    word_count = len(words)

    if word_count == 0:
        return {
            "score": 0.5,
            "sentence_variance": 0.0,
            "ttr": 0.0,
            "punct_density": 0.0,
            "punct_variety": 0,
            "word_count": 0,
            "note": "no analyzable words; stylometry unreliable",
        }

    # --- Sub-metric 1: sentence-length uniformity ---------------------------
    sentences = [s for s in _SENTENCE_SPLIT.split(text) if s.strip()]
    sent_lengths = [len(_WORD_RE.findall(s)) for s in sentences]
    sent_lengths = [n for n in sent_lengths if n > 0]
    mean_len = _mean(sent_lengths)
    # Coefficient of variation: std relative to mean. Low CV = uniform = AI-like.
    cv = (_std(sent_lengths) / mean_len) if mean_len > 0 else 0.0
    ai_variance = _clamp(1.0 - cv)

    # --- Sub-metric 2: type-token ratio (lexical diversity) ----------------
    ttr = len(set(words)) / word_count
    # Map TTR onto [0,1]: TTR<=0.3 very repetitive -> AI; TTR>=0.7 diverse -> human.
    ai_ttr = _clamp((0.7 - ttr) / 0.4)

    # --- Sub-metric 3: punctuation regularity ------------------------------
    punct_chars = [c for c in text if c in _PUNCT_MARKS]
    punct_density = len(punct_chars) / word_count
    punct_variety = len(set(punct_chars))
    # Few distinct mark types -> regular -> AI-like. 5+ types reads as human.
    ai_punct = _clamp(1.0 - punct_variety / 5.0)

    score = _mean([ai_variance, ai_ttr, ai_punct])

    result = {
        "score": round(score, 3),
        "sentence_variance": round(cv, 3),
        "ttr": round(ttr, 3),
        "punct_density": round(punct_density, 3),
        "punct_variety": punct_variety,
        "word_count": word_count,
    }
    if word_count < MIN_WORDS_FOR_STYLOMETRY:
        result["note"] = "text too short for reliable stylometry"
    return result


# ---------------------------------------------------------------------------
# Signal 2: LLM classifier (semantic) — Groq llama-3.3-70b-versatile
# ---------------------------------------------------------------------------

_LLM_SYSTEM = (
    "You are an expert forensic linguist. You assess whether a piece of text was "
    "written by a human or generated by an AI language model. You are calibrated "
    "and cautious: you avoid over-claiming, because falsely accusing a human "
    "writer of using AI is a serious harm."
)

_LLM_PROMPT = (
    "Assess the text below. Estimate the probability that it was generated by an "
    "AI language model rather than written by a human.\n\n"
    "Respond with ONLY a JSON object, no other text, of the exact form:\n"
    '{{"p_ai": <number from 0 to 1>, "rationale": "<one short sentence>"}}\n\n'
    "0 means clearly human, 1 means clearly AI, 0.5 means genuinely unsure.\n\n"
    'TEXT:\n"""\n{text}\n"""'
)


def _parse_llm_response(content):
    """Coerce the model's reply into {score, rationale}, tolerating stray text."""
    try:
        data = json.loads(content)
        p = float(data["p_ai"])
        rationale = data.get("rationale")
    except Exception:
        match = re.search(r"([01](?:\.\d+)?|0?\.\d+)", content or "")
        if not match:
            return {"score": None, "rationale": None,
                    "error": "could not parse LLM response", "raw": content}
        p = float(match.group(1))
        rationale = (content or "").strip()[:200]
    p = max(0.0, min(1.0, p))
    return {"score": round(p, 3), "rationale": rationale}


def llm_score(text, client=None):
    """Signal 2: ask an LLM whether the text reads as AI-generated.

    Returns {score in [0,1] (higher = more AI-like), rationale}. On any failure
    (missing key, network, unparseable reply) returns {score: None, error: ...}
    so the pipeline can degrade gracefully to the stylometric signal alone.

    `client` may be injected for testing without a live API call.
    """
    try:
        if client is None:
            api_key = os.environ.get("GROQ_API_KEY")
            if not api_key:
                return {"score": None, "rationale": None,
                        "error": "GROQ_API_KEY not set"}
            from groq import Groq

            client = Groq(api_key=api_key)

        resp = client.chat.completions.create(
            model=LLM_MODEL,
            temperature=0,
            max_tokens=200,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _LLM_SYSTEM},
                {"role": "user", "content": _LLM_PROMPT.format(text=text)},
            ],
        )
        return _parse_llm_response(resp.choices[0].message.content)
    except Exception as exc:  # noqa: BLE001 - any failure -> graceful fallback
        return {"score": None, "rationale": None,
                "error": f"{type(exc).__name__}: {exc}"}
